/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',    
    './src/layout/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',    
  ],
  theme: {
    screens: {
      '2xl': {'min': '1650px' },
      'xl': {'min': '1300px', 'max': '1649px',},
      'lg': {'min': '1030px', 'max': '1299px',},
      'md': {'min': '740px', 'max': '1029px',},
      'sm': {'min': '600px', 'max': '739px',},
      'ss': {'min': '320px', 'max': '599px',},
    },

    minWidth: {
      '1/3': '33.333333%',
    },
    fontFamily: {
      'helve': ['Helvetica', 'Arial', 'sans-serif'],
      'open': ['Open sans', 'sans-serif'],
      'myriad-pro': ['Myriad Pro', 'sans', 'bold'],
    },
    extend: {
      colors: {
        'libellum-text-gray': '#61676E',
        'libellum-border': '#E2E5E9',
        'libellum-light-blue': '#4DA8F0',
        'icons-gray': '#B2B2B2',
        'icons-menu': '#CECECE',
        'dark-blue': '#223955',
        'gray_alter': '#A2ACB7',
        /* 'libellum': '#0082c9', // IMEC */
        'libellum': '#0082c9', // SCOIL
        /* 'libellum': '#EDF6CD', // GLOBE */
        'form-btns': '#262E3B',
        'form-bg': '#F7F8F9',
        'btn-image': '#00A3FF',
        'shadow-trans': '#3336',
        'gray-light': '#F7F8F9',
        'gray-menu': '#C0C1C2',
        'gray-menu-text': '#939FAD',
        'blue-menu': '#189DFF',
        'btn-green': '#48BA17',
        'gray-mutted': '#5F676F',
        'dark-blue-menu': '#112B4A',
        'text-placeholder': '#BAC2CB',
        'switch-inactive': '#D0D0D0',
        'th': '#888888',
        'item-non': '#F0F0F0',
        'libellum-body': '#F6F8F9',
        // 'red-btn': '#DE0000',
        // 'red-hover': '#FC0000',
        'red-btn': '#0082c9',
        'red-hover': '#0082c9',
        'green-btn': '#7BAA20',
        'green-hover': '#ACD80E',
        'libellum-form': '#F2F4F5',
        'icon-home': '#555657',
        'error-warning': '#FE7F01',
        'agenda-borde': '#EFF0F3',
        'star': '#FEBC01',
        'message': '#606060',
        'more-hor': '#96A1AE',
        'btn-sky-blue': '#61B2F2',
        'apps': '#0082c9', // SCOIL e IMEC
        /* 'apps': '#9CA34C', // GLOBE */
        'icon-dark': '#232429',
        'dark-text': '#D0D0D0',
        'libellum-dark-v': '#151519',
        'dark-border': '#3E424D',
        'input-dark': '#282E3A',
        'placeholder-dark': '#AFAFAF',
        'non-dark': '#1E1F24',
        'libellum-gray': '#808080',
        
        'libellum-light': '#0082c9',
        'libellum-title': '#40536B',
        'libellum-light-green': '#ACD80E',
        'libellum-dark': '#585858',
        'btn-blue': '#3A84BF',
        
        'libellum-gray-2': '#A5A5A5',
        'red-card': '#990000',

        'btn-green-light': '#A3C91B',
        'txtbtn-gray': '#707070',
        'input-white': '#FFFFFF',
        'input-label-gray': '#464646',
        'btn-del-gray': '#242E3C',
        'btn-del-hover': '#FC0000',
        'txt-dark-blue': '#2F4958',
        'txt-red': '#FA5555',
        'txt-blue' : '#437BE0',
        'txt-purple': '#8F4EE1',
        'txt-blue-company': '#5B7B98',
        'txt-blue-sesion': '#3D537B',
        'txt-gray-list': '#8D8D8D',
        'txt-black' : '#000000',
        //SCOIL
        'input-gray' : '#676767',
        'btn-input-white' : '#F4F4EF',
        'btn-back-cursor' : '#63A9F0',
        'select-gray' : '#545D67',
        'txt-search' : '#62676D',
        'btn-purple' : '#4A61CE', 
        'red-notification' : '#FF0303',
        'gray-checked' : '#BFBDBD',        
        'blue-hover' : '#60B2F2',
        'blue-scoil' : '#223455',
        'green-scoil' : '#80BF1B',
        'section-title' : '#3E3E3E',
        'light-purple' : '#9392C1',
        'black-mat' : '#535353',
        'gray-mat' : '#818181',
        'purple-mat' : '#6781FE',
        'yellow-mat' : '#FEC401',
        'red-mat' : '#FC0000',
        'red-date' : '#DE0000',
        'gray-cal' : '#B5B9BE',
        'gray-not' : '#E6E6E6',
        'yellow-not' : '#FFB443',
        'yellow-bar' : '#FED443',
        'gray-not-text' : '#939393',
        'gray-not-line' : '#939393',
        'blue-header-table' : '#011873',
        'gray-message' : '#95958E',

        'body-chat': '#7E7E7E',
        'chat-bg': '#E5E8ED',
        'chat-name': '#8491A5',
        'chat-border': '#DBDBDB',
        'morado': '#E7DDFF',
        'azul': '#E8F3FF',
        'pink-th' : '#E7DDFF',
        'blue-th' : '#E8F3FF',
        'gray-cancel' : '#BFBFBF',
        'red-indicator' : '#FF0000',
        'gray-amount' : '#BBBABC',
        'green-pay' : '#B2D326',
        'blue-resend' : '#104A96',
        'image-blue' : '#1385C8',
        'back-blue' : '#3A84BF',
      },      
      backgroundColor: ['even', 'odd']
    },
  },
  plugins: [],
}
